{% set name = "spatialmath-python" %}
{% set version = "1.1.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1b5b0cdc8dfb660f8cf21e7ce8e56fd0987ecf7276bef3811514720c7e021351
  patches:
    - avoid-strict-pinning.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - ansitable
    - colored <1.5.0
    - matplotlib-base
    - numpy
    - python >=3.7
    - scipy
    - sympy
    - sphinxcontrib-jsmath
    - typing-extensions
    - pre_commit

test:
  imports:
    - spatialmath
    - spatialmath.base
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bdaiinstitute/spatialmath-python
  summary: Provides spatial maths capability for Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - petercorke
