{% set name = "spatialmath-python" %}
{% set version = "1.1.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ee1dbd4470abc5d7b1a5a6edc4c431ffb45a8509820c61e1749d56113bed7d88

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ansitable
    - colored <1.5.0
    - matplotlib-base
    - numpy
    - python >=3.6
    - scipy
    - sympy
    - sphinxcontrib-jsmath
    - typing-extensions
    - pre_commit

test:
  imports:
    - spatialmath
    - spatialmath.base
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/petercorke/spatialmath-python
  summary: Provides spatial maths capability for Python.
  dev_url: https://github.com/petercorke/spatialmath-python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - petercorke
